/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ticktockdata.jasper.prompts;

import java.util.Date;

/**
 *
 * @author default
 */
public class DatePrompt extends PromptComponent<java.util.Date> {

    /**
     * Creates new form DatePrompt
     */
    public DatePrompt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescription = new javax.swing.JLabel();
        datePicker = new classicacctapp.ClassicAccDatePicker();

        lblDescription.setText("Date");

        datePicker.setFormats("MM/dd/yy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Date getPromptValue() {
        return datePicker.getDate();
    }

    @Override
    public void setPromptValue(Date value) {
        datePicker.setDate(value);
    }

    @Override
    public void setDescription(String description) {
        super.setDescription(description);
        lblDescription.setText(description);
    }
    
    
    
    
    @Override
    public void refreshData() {
        
        System.out.println("refreshData() for DatePrompt - do nothing.");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private classicacctapp.ClassicAccDatePicker datePicker;
    private javax.swing.JLabel lblDescription;
    // End of variables declaration//GEN-END:variables
}
