/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ticktockdata.jasper.gui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.io.File;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author JAM {javajoe@programmer.net}
 */
public class ReportsPanel extends javax.swing.JPanel {

    String rootDir;

    public ReportsPanel() {
        // netbeans
    }
    
    /**
     * Creates new form ReportsPanel
     */
    public ReportsPanel(String rootPath) {
        this.rootDir = rootPath;
        initComponents();
        initReportPanels();
    }

    /**
     *
     * @return number of report buttons created, or -1 if error;
     */
    private int initReportPanels() {

        int ct = 0;

        try {
            // first remove all old components
            for (Component c : pnlTabPane.getComponents()) {
                pnlTabPane.remove(c);
            }

            // create a file of the root directory
            File rf = new File(rootDir);
            if (rf == null || !rf.exists() || !rf.isDirectory()) {
                System.out.println("Not a valid directory!");
                return -1;  // error
            }

            // list the directories only
            File[] allDirs = rf.listFiles(File::isDirectory);
            // sort the directories alphabetically
            Arrays.sort(allDirs);

            // list all directories within this directory
            for (File reportDir : allDirs) {

                // list all reports
                File[] reports = reportDir.listFiles((File ff) -> {
                    return !ff.isDirectory() && ff.getName().toLowerCase().endsWith(".jrxml") && !ff.getName().startsWith("_");
                });
                
                if (reports.length <= 0) continue;
                
                // sort the report list
                Arrays.sort(reports);
                
                // create the panel for this directory's reports
                JPanel panel = new JPanel();
                panel.setMinimumSize(new Dimension(100, 200));
                panel.setName(reportDir.getName());
                FlowLayout fl = new FlowLayout(FlowLayout.LEADING, 12, 12);
                panel.setLayout(fl);

                for (File rpt : reports) {
                    // create a button for this report and add to panel
                    //JButton btn = new JButton(rpt.getName());
                    ReportButton pb = new ReportButton(rpt);
                    //pb.setReport(rpt.getCanonicalPath());
                    panel.add(pb);
                }

                // add this panel to the Tab Pane
                pnlTabPane.add(panel);

            }

        } catch (Exception ex) {
            System.out.println("Error occurred during loading reports: " + ex.getLocalizedMessage());
            ex.printStackTrace();
            return -1;  // error
        }

        return ct;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTabPane = new javax.swing.JTabbedPane();

        pnlTabPane.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        JFrame jf = new JFrame("Tester");
        jf.setMinimumSize(new Dimension(600, 400));
        jf.setPreferredSize(new Dimension(800, 600));
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        jf.add(new ReportsPanel("/home/default/JoeWatch/ClassicUtils/"));
        jf.setLocation(400, 300);

        jf.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane pnlTabPane;
    // End of variables declaration//GEN-END:variables
}
